version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: backend-fiap-postgres
    environment:
      POSTGRES_DB: backendfiap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend-fiap-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backendfiap
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      OPENWEATHER_API_KEY: 2e5f8e562a18f9ea7bd09eae6f340b9a
      FIREBASE_CONFIG_PATH: /app/resources/fiapbackend-firebase-adminsdk-563fl-32ee904e6e.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
